title: Michael Corey, data journalist
description: >
  **Michael Corey**, is a data journalist
  who likes maps, science and history.
copyright: 2016 Michael Corey
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: stratajekylldemo
facebook_username:
twitter_username: "mikejcorey"
linkedin_username:
instagram_username:
pinterest_username:
flickr_username:
github_username:  "mikejcorey"
feed_icon: rss
email: "mikejcorey@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
